import test from 'node:test';import assert from 'node:assert/strict';
import {scenarios} from '../src/scenarios.js';import {makeDraw,replacePair,compare,encodeDraw,decodeDraw,optionOrder} from '../src/engine.js';
test('200 bilingual scenarios with complete comparable variants',()=>{assert.equal(scenarios.length,200);assert.equal(new Set(scenarios.map(s=>s.id)).size,200);assert.equal(new Set(scenarios.map(s=>s.theme)).size,25);for(const s of scenarios)for(const lang of ['fr','en']){assert.equal(s[lang].options.length,4);assert.equal(s[lang].identities.length,2);assert.notEqual(...s[lang].identities);assert.ok(s[lang].action&&s[lang].context)}});
test('draws are repeatable, have 5 distinct themes and separated pairs',()=>{for(let seed=0;seed<300;seed++){const q=makeDraw(seed);assert.deepEqual(q,makeDraw(seed));assert.equal(q.length,10);assert.equal(new Set(q.map(x=>x.id)).size,5);assert.equal(new Set(q.map(x=>scenarios.find(s=>s.id===x.id).theme)).size,5);for(let i=0;i<5;i++){const j=q.findIndex((item,k)=>k>=5&&item.id===q[i].id);assert.ok(j-i>=3);assert.notEqual(q[i].variant,q[j].variant)}assert.notDeepEqual(q.slice(0,5).map(x=>x.id),q.slice(5).map(x=>x.id));assert.deepEqual(decodeDraw(encodeDraw(q)),q)}});
test('gentle mode excludes sensitive themes',()=>{for(let seed=0;seed<100;seed++)for(const q of makeDraw(seed,true))assert.equal(scenarios.find(s=>s.id===q.id).sensitive,false)});
test('replacement changes both copies without extra questions or repeated themes',()=>{const q=makeDraw(19),r=replacePair(q,0,19);assert.equal(r.length,10);assert.notEqual(r[0].id,q[0].id);assert.equal(r.filter(x=>x.id===r[0].id).length,2);assert.equal(scenarios.find(s=>s.id===r[0].id).sensitive,false);assert.equal(new Set(r.map(x=>scenarios.find(s=>s.id===x.id).theme)).size,5)});
test('comparison maps answers to identities rather than order',()=>{const q=makeDraw(39);const consistent=q.map(x=>x.id.length%4);assert.equal(compare(q,consistent).filter(p=>p.changed).length,0);const changed=consistent.map((x,i)=>i>=5?(x+1)%4:x);assert.equal(compare(q,changed).filter(p=>p.changed).length,5);for(const p of compare(q,changed))for(let v=0;v<2;v++)assert.equal(p.selected[v],changed[q.findIndex(x=>x.id===p.scenario.id&&x.variant===v)])});
test('untrusted share payloads are rejected',()=>{for(const s of [null,'','<script>','999.0-0.1','0.0-0.0-0.0-0.0-0.0-0.0-0.0-0.0-0.0-0.0','1.0-1.1-2.0-2.1-3.0-3.1-4.0-4.1-5.0-5.2'])assert.equal(decodeDraw(s),null)});

test('every bilingual scenario uses short copy and short answers',()=>{for(const scenario of scenarios)for(const lang of ['fr','en']){const d=scenario[lang];assert.ok(d.prompt);assert.ok(d.action.length<190,scenario.id);assert.ok(d.options.every(option=>option.length<=34),scenario.id)}});

test('each situation contains distinct facts in both languages',()=>{for(const lang of ['fr','en'])assert.equal(new Set(scenarios.map(s=>s[lang].action)).size,200)});
test('option positions change while shared draws keep identical presentation',()=>{for(let seed=0;seed<100;seed++){const q=makeDraw(seed),shared=decodeDraw(encodeDraw(q));for(let i=0;i<10;i++){const order=optionOrder(q,i);assert.deepEqual([...order].sort(),[0,1,2,3]);assert.deepEqual(order,optionOrder(shared,i));const j=q.findIndex((item,k)=>k!==i&&item.id===q[i].id);assert.notDeepEqual(order,optionOrder(q,j))}}});

test('clicking the same screen position cannot substitute for answering each situation',()=>{for(let seed=0;seed<30;seed++){const q=makeDraw(seed);const answers=q.map((_,i)=>optionOrder(q,i)[0]);assert.equal(compare(q,answers).filter(p=>p.changed).length,5)}});
