import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/space-grotesk/400.css';
import '@fontsource/space-grotesk/600.css';
import '@fontsource/space-grotesk/700.css';
import './style.css';
import {scenarios} from './scenarios.js';
import {makeDraw,newSeed,replacePair,compare,encodeDraw,decodeDraw} from './engine.js';
const app=document.querySelector('#app');
let lang='fr',page='home',seed=newSeed(),questions=[],answers=[],index=0,gentle=false,replacements=0;
const params=new URLSearchParams(location.search);const incoming=decodeDraw(params.get('draw'));if(params.get('lang')==='en')lang='en';
const t=(fr,en)=>lang==='fr'?fr:en;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo=`<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M20 5v27M8 13h24M20 8l-12 5m12-5 12 5M8 14l-6 12h12L8 14Zm24 0-6 12h12l-6-12ZM12 35h16" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/></svg>`;
function header(){return `<header><button class="brand" data-action="home" aria-label="${t('Accueil','Home')}">${logo}<span>DEUX POIDS,<br>DEUX MESURES.</span></button><nav class="nav"><button class="link" data-action="about">${t('Le principe','The idea')} ↗</button><button class="lang" data-action="language" aria-label="${t('Switch to English','Passer en français')}">${lang==='fr'?'FR <span style="opacity:.4">/ EN</span>':'EN <span style="opacity:.4">/ FR</span>'}</button></nav></header>`}
function footer(){return `<footer><span>© ${new Date().getFullYear()} Deux poids, deux mesures.</span><span>${t('Sans compte. Sans collecte. Sans étiquette.','No account. No collection. No labels.')}</span><button class="link" data-action="privacy">${t('Confidentialité','Privacy')}</button></footer>`}
function home(){return `<main class="home animate"><div class="eyebrow"><span class="dot"></span>${t('10 CHOIX. UNE SURPRISE.','10 CHOICES. ONE SURPRISE.')}</div><h1>${t('Tu juges vite.<br>Tu juges <em>juste ?</em>','Quick to judge.<br>Always <em>fair?</em>')}</h1><p class="intro">${t('Deux minutes. Ton instinct. Et une surprise à la fin.','Two minutes. Your instinct. A surprise at the end.')}</p><button class="primary start-button" data-action="start">${incoming?t('Relever le défi','Take the challenge'):t('C’est parti','Let’s go')} <span>↗</span></button><div class="home-meta"><span>${t('10 questions','10 questions')}</span><span>${t('4 choix','4 choices')}</span><span>${t('Sans compte','No account')}</span></div><section class="demo-board" aria-label="${t('Essaye les quatre cases','Try the four tiles')}"><div class="demo-top"><span class="eyebrow">${t('UN PETIT ÉCHAUFFEMENT','A QUICK WARM-UP')}</span><span class="demo-label">${t('Hors test','Not scored')}</span></div><h2>${t('Quelqu’un double la file.<br>Tu fais quoi ?','Someone jumps the queue.<br>What do you do?')}</h2><div class="choices demo-choices">${[t('Je laisse passer','Let it slide'),t('Je lui dis','Say something'),t('J’appelle le personnel','Call a staff member'),t('Je quitte la file','Leave the queue')].map((o,i)=>`<button class="choice" data-demo="${i}" aria-pressed="false"><span class="tile-number">0${i+1}</span><span class="choice-label">${o}</span><span class="tile-arrow" aria-hidden="true">↗</span></button>`).join('')}</div><p id="demo-feedback" class="demo-feedback" role="status">${t('Touche une case. C’est aussi simple que ça.','Tap a tile. That’s all there is to it.')}</p></section><section id="principle" class="home-bottom"><label class="gentle-toggle"><input id="gentle" type="checkbox" ${gentle?'checked':''} ${incoming?'disabled':''}><span>${t('Sans thèmes de violence','No violence topics')}</span></label><p class="note">${t('Situations fictives. Sujets sensibles sans détails graphiques.','Fictional situations. Sensitive topics without graphic details.')}</p><span class="bank-label">${t('200 situations · FR / EN','200 situations · FR / EN')}</span></section></main>`}
function question(){const q=questions[index],s=scenarios.find(s=>s.id===q.id),d=s[lang];return `<main class="test quiz animate"><div class="test-top"><span>${t('À TOI DE JUGER','YOUR CALL')}</span><span>${index+1} / 10</span></div><div class="progress" role="progressbar" aria-label="${t('Progression','Progress')}" aria-valuenow="${index}" aria-valuemin="0" aria-valuemax="10"><div style="width:${index*10}%"></div></div><div class="question-card"><div class="question-topic"><span class="topic-icon" aria-hidden="true">${s.sensitive?'!':'?'}</span><span>${escape(d.title)}</span></div><div class="setting">${escape(d.context)}</div><p class="scenario"><strong>${escape(d.identities[q.variant].charAt(0).toUpperCase()+d.identities[q.variant].slice(1))}</strong> ${escape(d.action)}</p></div><h2 class="prompt">${escape(d.prompt)}</h2><div class="choices">${d.options.map((o,i)=>`<button class="choice" data-answer="${i}"><span class="tile-number">0${i+1}</span><span class="choice-label">${escape(o)}</span><span class="tile-arrow" aria-hidden="true">↗</span></button>`).join('')}</div><div class="test-actions"><span class="micro">${t('Touche une case.','Tap a tile.')}</span>${!questions.slice(0,index).some(x=>x.id===q.id)?`<button class="link" data-action="replace">${t('Changer de situation','Change situation')} ↻</button>`:''}</div><div class="quiz-dots" aria-hidden="true">${Array.from({length:10},(_,i)=>`<span class="${i<index?'done':i===index?'current':''}"></span>`).join('')}</div></main>`}
function result(){const pairs=compare(questions,answers),count=pairs.filter(p=>p.changed).length;return `<main class="test results animate"><div class="result-head"><div class="eyebrow">${t('LE RETOURNEMENT','THE TWIST')}</div><h2>${count?t('Tu as changé de réponse.','You changed your answer.'):t('Tu as gardé le même cap.','You stayed consistent.')}</h2><div class="score">${count}<span> / 5</span></div><p>${t('Mêmes faits. Autre identité.<br>Chaque situation est revenue deux fois.','Same facts. Different identity.<br>Each situation appeared twice.')}</p></div><div class="share"><button class="primary" data-action="share">${t('Défier mes amis','Challenge my friends')} ↗</button><button class="secondary" data-action="restart">${t('Rejouer','Play again')} ↻</button></div><p class="note share-note">${t('Le défi partage les questions. Jamais tes réponses.','The challenge shares questions. Never your answers.')}</p><div id="share-fallback"></div><h3 class="comparison-title">${t('Voilà ce qui a changé.','Here’s what changed.')}</h3>${pairs.map(p=>{const d=p.scenario[lang];return `<article class="comparison"><div class="comparison-top"><h3>${escape(d.title)}</h3><span class="badge ${p.changed?'changed':''}">${p.changed?t('Différent','Different'):t('Identique','Same')}</span></div><div class="pair">${[0,1].map(v=>`<div><p>${escape(d.identities[v])}</p><strong>${escape(d.options[p.selected[v]])}</strong></div>`).join('')}</div><details><summary>${t('Revoir les faits','Review the facts')}</summary><p class="note">${escape(d.context)}. ${escape(d.action)}</p></details></article>`}).join('')}<div class="notice">${t('Cinq comparaisons, pas une étiquette. Ce test invite à réfléchir. Ce n’est pas un diagnostic.','Five comparisons, not a label. This test invites reflection. It is not a diagnosis.')}<details><summary>${t('Comprendre le résultat','About your result')}</summary><p>${t('Une réponse différente peut venir de l’attention, de l’hésitation ou du contexte perçu. Ce test n’est pas une mesure scientifique validée des préjugés.','A different answer may come from attention, hesitation or perceived context. This is not a scientifically validated measure of bias.')}</p></details></div></main>`}
function privacy(){return `<main class="test animate"><h2>${t('Tes réponses t’appartiennent.','Your answers belong to you.')}</h2><p class="scenario">${t('Aucun compte, cookie, outil de suivi ou serveur de résultats. Tes réponses restent en mémoire dans cet onglet et disparaissent si tu recharges la page. Le lien de défi contient seulement les identifiants des questions et leur ordre.','No account, cookies, tracking tools or results server. Your answers stay in this tab’s memory and disappear when you reload. A challenge link contains only question identifiers and their order.')}</p><p class="note">${t('Les polices sont intégrées au site. L’hébergeur peut conserver ses journaux techniques de connexion.','Fonts are bundled with the site. The site host may retain technical connection logs.')}</p><button class="secondary" data-action="return">${t('Retour','Back')}</button></main>`}
let previousPage='home',answering=false;
function render(){document.documentElement.lang=lang;document.body.dataset.page=page;app.innerHTML=header()+(page==='home'?home():page==='question'?question():page==='privacy'?privacy():result())+footer();app.innerHTML=app.innerHTML.replaceAll('↗','<svg width="16" height="16" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12" stroke="currentColor" stroke-width="2"/></svg>');app.querySelectorAll('h2').forEach(h=>h.tabIndex=-1);}
function toast(message){document.querySelector('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.setAttribute('role','status');e.textContent=message;document.body.append(e);setTimeout(()=>e.remove(),3200)}
function start(fresh=false){seed=newSeed();questions=!fresh&&incoming?incoming.map(q=>({...q})):makeDraw(seed,gentle);answers=[];index=0;replacements=0;page='question';render();window.scrollTo(0,0)}
app.addEventListener('change',e=>{if(e.target.id==='gentle')gentle=e.target.checked});
app.addEventListener('click',async e=>{const button=e.target.closest('button');if(!button||answering)return;if(button.dataset.demo!==undefined){app.querySelectorAll('[data-demo]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button))});document.querySelector('#demo-feedback').textContent=t('Voilà. Maintenant, place au vrai test !','That’s it. Now try the real test!');return}if(button.dataset.answer!==undefined){answering=true;const answer=Number(button.dataset.answer);button.classList.add('selected');app.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)await new Promise(resolve=>setTimeout(resolve,180));answers.push(answer);index++;page=index===10?'result':'question';render();answering=false;window.scrollTo(0,0);app.querySelector('main h2')?.focus({preventScroll:true});return}switch(button.dataset.action){case 'start':start();break;case 'restart':start(true);break;case 'language':lang=lang==='fr'?'en':'fr';render();break;case 'home':if(page==='question'&&!confirm(t('Quitter le test ? Tes réponses seront perdues.','Leave the test? Your answers will be lost.')))return;page='home';render();window.scrollTo(0,0);break;case 'about':if(page!=='home'){if(page==='question'&&!confirm(t('Quitter le test ?','Leave the test?')))return;page='home';render()}document.querySelector('#principle').scrollIntoView({behavior:'smooth'});break;case 'replace':questions=replacePair(questions,index,seed+(++replacements)*7919);render();toast(t('Situation remplacée pour ce tirage.','Situation replaced for this draw.'));break;case 'privacy':previousPage=page;page='privacy';render();window.scrollTo(0,0);break;case 'return':page=previousPage;render();break;case 'share':{const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('draw',encodeDraw(questions));url.searchParams.set('lang',lang);try{await navigator.clipboard.writeText(url.href);toast(t('Lien du défi copié !','Challenge link copied!'))}catch{document.querySelector('#share-fallback').innerHTML=`<label class="note">${t('Copie ce lien :','Copy this link:')}<input aria-label="${t('Lien du défi','Challenge link')}" readonly style="width:100%;padding:14px;margin-top:10px" value="${escape(url.href)}"></label>`;document.querySelector('#share-fallback input').select()}break}}});
if(params.has('draw')&&!incoming)setTimeout(()=>toast(t('Lien invalide : un nouveau tirage sera proposé.','Invalid link: a new draw will be offered.')),100);
render();
